<?php


namespace App\Admin\BotMessageAdmin;


use App\Entity\Intent;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class UtteranceAdmin extends AbstractAdmin
{

    protected function configureListFields(ListMapper $list)
    {
        $list->add("id")
            ->add('text')
            ->add('intent',null,array('associated_toString' => 'getIntent'))
            ->add('Actions','actions',[
                'actions' => [
                    'show' => [],
                    'edit' => [],
                    'delete' => []
                ]
            ]);

    }

    protected function configureFormFields(FormMapper $form)
    {
        $form->add('intent',EntityType::class, [
                'class' => Intent::class,
                'choice_label' => 'label'
            ])
            ->add('text', TextareaType::class);
    }

    public function configureActionButtons($action, $object = null)
    {
        return parent::configureActionButtons($action, $object); // TODO: Change the autogenerated stub
    }


}